// schema for database objects
export const HealthCampSchema = {
  name: 'HealthCamp',
  properties: {
    _id: 'int',
    agent_id: 'int',
    isNew: 'bool',
    name: 'string?',
    location: 'string?',
    block: 'string?',
    district: 'string?',
    state: 'string?',
    partnerID: 'int?',
    type: 'int',
    health_camp_date: 'string',
    serial_no: 'string',
    childName: 'string',
    contact: 'string',
    gender: 'string',
    beneficiaryID: 'int',
    age_editable: 'bool',
    dob: 'string?',
    age: 'string',
    height: 'string',
    weight: 'string',
    muac: 'string',
    education: 'int',
    vitamin_A: 'bool',
    vitamin_A_done_by: 'string?',
    vitamin_A_duration: 'string?',
    vitamin_A_location: 'string?',
    vitamin_A_dose_date: 'string?',
    deworming: 'bool',
    deworming_done_by: 'string?',
    deworming_duration: 'string?',
    deworming_location: 'string?',
    deworming_dose_date: 'string?',
    ifa: 'bool',
    ifa_done_by: 'string?',
    ifa_duration: 'string?',
    ifa_location: 'string?',
    ifa_dose_date: 'string?',
    images: {
      type: 'list', // Realm List type for storing an array of objects
      objectType: 'ImagesSchema', // Reference the schema for image data
    },
  },
  primaryKey: '_id',
};
